import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Button from "./layouts/core/button";
import { killAll } from "@/services/localStorage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AppBar = () => {
  return (
    <header className="bg-black-900 text-white-700 py-2 px-6 flex justify-between items-center border-b border-white-100">
      <div className="text-sm md:text-base font-semibold">
        <a href="/">
          <Image
            className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
            src="/next.svg"
            alt="Next.js Logo"
            width={100}
            height={30}
            priority
          />
        </a>
      </div>
      <nav>
        <ul className="flex space-x-2 md:space-x-3">
          <li className="hover:text-white-900">
            <a
              href="/authentication/mvc"
              className="text-white text-md md:text-md hover:underline"
            >
              MVC
            </a>
          </li>
          <li className="hover:text-white-900">
            <a
              href="/authentication/mvvm"
              className="text-white text-md md:text-md hover:underline"
            >
              MVVM
            </a>
          </li>
          <li className="hover:text-white-900">
            <a
              href="/authentication/mvp"
              className="text-white text-md md:text-md hover:underline"
            >
              MVP
            </a>
          </li>
          <li className="hover:text-white-900">
            <a
              href="/authentication/viper"
              className="text-white text-md md:text-md hover:underline"
            >
              VIPER
            </a>
          </li>
        </ul>
      </nav>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className="bg-black-900 text-white-700 py-4 px-6 text-center border-t border-white-100">
      <p>&copy; 2024 My Next.js App. All rights reserved.</p>
      <p className="text-sm mt-2">Built with Next.js and Tailwind CSS</p>
    </footer>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
